# Generated by Django 6.0.3 on 2026-03-18 19:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('9d43ca29-bbae-4317-88c0-58fe223fd377'))),
                ('full_url', models.URLField()),
                ('short_url', models.URLField()),
            ],
        ),
    ]
