# Generated by Django 6.0.3 on 2026-03-19 14:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcutter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shorturlmodel',
            options={'verbose_name': 'Short URL', 'verbose_name_plural': "Short URL's"},
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='short_url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('79b4c0be-4344-4c78-899f-fadd7e39d4cf')),
        ),
        migrations.CreateModel(
            name='ClickModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('country', models.CharField(max_length=200, null=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortcutter.shorturlmodel')),
            ],
            options={
                'verbose_name': 'Information about the click on the short URL',
                'verbose_name_plural': 'Information about the clicks on the short URL',
                'get_latest_by': 'click_at',
            },
        ),
    ]
