# Generated by Django 6.0.3 on 2026-03-20 12:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcutter', '0002_alter_shorturlmodel_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturlmodel',
            old_name='short_url',
            new_name='short_code',
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('47f44557-9136-47be-8ecb-2337e5805856')),
        ),
    ]
