# Generated by Django 6.0.3 on 2026-03-22 15:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcutter', '0003_rename_short_url_shorturlmodel_short_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickmodel',
            name='ip_address',
        ),
        migrations.AlterField(
            model_name='clickmodel',
            name='click_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='short_code',
            field=models.CharField(default='neDUnM', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('432afbdc-8303-4de4-b214-688fa3c29af6')),
        ),
    ]
