# Generated by Django 6.0.3 on 2026-03-23 13:20

import django.db.models.deletion
import shortcutter.utils
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortcutter', '0004_remove_clickmodel_ip_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturlmodel',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, to_field='uuid'),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='short_code',
            field=models.CharField(default=shortcutter.utils.get_short_code, max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='shorturlmodel',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
